### ISSUE TITLE
More useful hints?

### ISSUE THREAD

**Issue by Haroenv** [Vincenius/css-speedrun#3]
I wonder if a more useful hint that had some time penalty, like "think of :nth-of-type" would help? Or maybe explaining slightly what the pattern is without saying the actual solution

**Comment by Vincenius** [comment]
I'll improve the hints somewhen this week - but time penalties are not planned

**Comment by Vincenius** [comment]
There are now two hints on each level - the first one gives a small tooltip with text and the second one is the MDN link

<img width="439" alt="Screenshot 2022-01-21 at 08 21 12" src="https://user-images.githubusercontent.com/43953403/150483884-cc128802-60c5-46ba-8cfa-fa12db7951af.png">
