### ISSUE TITLE
Show ideal solutions

### ISSUE THREAD

**Issue by graup** [Vincenius/css-speedrun#4]
Many of the puzzles can be "solved" quicker in a hacky way than in an ideal way. To actually teach something, after the game is done, it would be great to show intended (ideal) solutions. 

From [HN](https://news.ycombinator.com/item?id=29966998) (not me):

> The intended solution is just :enabled. This is where I think this project has failed badly in its stated goal to “improve your CSS knowledge”, because all it offers in that direction is a little hint link; to actually teach, it needs a set of proposed solutions, and at the end show you any where you differed.
> Such a thing might also help suggesting just [data-item] instead of the needlessly-more-specific span[data-item]. And also whether :nth-child(2n+3) was the intended solution on one of them.

**Comment by Vincenius** [comment]
I'll take care of improved hints / show better solutions somewhen this week :)

**Comment by Vincenius** [comment]
<img width="784" alt="Screenshot 2022-01-18 at 09 23 09" src="https://user-images.githubusercontent.com/43953403/149899885-e0c13deb-ee7f-4c0d-857c-a23fab9c2964.png">

Done 👍
