### ISSUE TITLE
Barely visible "error line"

### ISSUE THREAD

**Issue by 0x04** [Vincenius/css-speedrun#6]
For me, it's that barely visible that I did not notice it for the first minutes. And even after I knew it, I could not recognize it immediately 😅

I didn't know if it is intended, but I think a richer red would be great.

![image](https://user-images.githubusercontent.com/1921383/150403161-bb8659ce-e493-490d-b2de-f3d824996570.png)

**Comment by Vincenius** [comment]
Thanks for the feedback - updated to error and success colors :)

<img width="432" alt="Screenshot 2022-01-21 at 07 21 01" src="https://user-images.githubusercontent.com/43953403/150476755-29a45975-3762-489a-96dc-2551f8c3c007.png">
